name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.0.12
  - notebook
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - ydata-profiling
  - ipywidgets
  - pyarrow=2.0
  - pip:
      - wandb==0.10.31
      - protobuf==3.20.1
      - flask==2.2.3